#6 - Zmiany w wyglądzie panelu rodzica, nowe komponenty typu tabela
praca-inz-pjjj/frontend pull request #19
Opened 2024-10-25 07:53 UTC by jaugustyn02

2024-10-25 08:20 UTC, jkr02 approved these changes
204 No content

2024-10-25 08:27 UTC, pwolan requested changes
Wydaje mi się, że to co zasugerowałem jest czytelniejsze. Szczególnie jak masz zagnieżdżony kolejny warunek

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/components/PickUpsTable.jsx
> +  )
```suggestion
  if(pickups_data && pickups_data.length === 0) {
      return  (
        <>
        <h3 className="text-xl font-semibold mb-4">{ title }</h3>
        <p className="text-gray-600 mb-8">{no_data_message}</p>
        </>
    )
  }
  return  (
    <div className="overflow-x-auto mb-8">
      <h3 className="text-xl font-semibold mb-4">{ title }</h3>
      <table className="min-w-full bg-white border border-gray-300">
        <thead>
          <tr>
            <th className="px-4 py-2 border-b border-gray-300 text-left">#</th>
            <th className="px-4 py-2 border-b border-gray-300 text-left">Imię</th>
            <th className="px-4 py-2 border-b border-gray-300 text-left">Nazwisko</th>
            <th className="px-4 py-2 border-b border-gray-300 text-left">Klasa</th>
            <th className="px-4 py-2 border-b border-gray-300 text-left">Więcej</th>
          </tr>
        </thead>
        <tbody>
          {pickups_data?.map((pickup, index) => (
            <tr key={pickup.id} className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b border-gray-300">{index + 1}</td>
              <td className="px-4 py-2 border-b border-gray-300">{pickup.name}</td>
              <td className="px-4 py-2 border-b border-gray-300">{pickup.surname}</td>
              <td className="px-4 py-2 border-b border-gray-300">{pickup.classroom_name}</td>
              <td className="px-4 py-2 border-b border-gray-300">
                <Link
                  to={`/parent/child/${pickup.id}`}
                  className="text-blue-500 hover:underline"
                >
                  Szczegóły
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
```

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/components/PermittedUsersTable.jsx
> +  return permitted_users_data && permitted_users_data.length === 0 ? (
Możesz przerobić tak jak w sugestii poniżej

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/components/ChildrenTable.jsx
> +    return children && children.length === 0 ? (
Możesz przerobić tak jak w sugestii poniżej

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/child/PermittedUsersTable.jsx
> +  return permitted_users_data && permitted_users_data.length === 0 ? (
Możesz przerobić tak jak w sugestii poniżej

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/child/ChildDetails.jsx
> +                ) : (
Możesz przerobić tak jak w sugestii poniżej

2024-10-25 08:27 UTC, pwolan commented on src/pages/parent/Home.jsx
> +      ) : (
Możesz przerobić tak jak w sugestii poniżej

2024-10-26 11:13 UTC, pwolan approved these changes

2024-10-26 11:13 UTC, merged